function msg = getMsgStr(thisphase)
switch(thisphase)
    case 'pre'
        msg={'Welcome to the experiment!'};
    case 'pract1'         % pract1
        msg={'Now, you will see a volume meter below the word.',...
			'',...
			'It will tell you how loud you''ve spoken. Please carefully',...
			'adjust you loudness to hit the middle green area. ',...
			'',...
			'A trial will be repeated until you successfully land in this area.',...
			'',...
			'Press "play" to continue.',...
			};
    case 'pract2'		% pract2
        msg={'Good job!',...
			'',...
			'Now, in addition to the volume meter, a speed meter is',...
			'displayed. It will tell you how fast you''ve spoken ',...
			'Please carefully adjust your word length to hit the middle green area',...
			'',...
			'A trial will be repeated until you simultaneously lands in the green ',...
			'areas of both the volume and speed meters. Press "play" to continue.'};
    case 'start'	% start
        msg={'Good job!',...
			'',...
			'Now, the trials will not repeat even if you fall out of the green areas.',...
			'However, please try to keep the volume and speed you''ve learned ',...
			'throughout the rest of the experiment.',...
			'',...
			'Press "play" to continue'};
    case 'ramp'
        msg={''};
    otherwise,
        msg={''};
end
    
