function msg = getMsgStr(bTrigByScanner, thisphase)
if bTrigByScanner == 0 % --- For behavioral sessions --- %
    if isequal(thisphase, 'pract1')
        msg={'Hi, there!', ...
             '', ...
             'When you see green font and the word "Normal", ', ...
             'read the sentence in a natural (non-rhythmic) way.', ...
             '', ...
             'When you see blue font and the word "Rhythm", ', ...
             'read the sentence in a rhythmic way, according to', ...
             'the beat heard before the sentence.', ...
             '', ...
             'After each sentence, you will see a bar that', ...
             'indicates whether you hit the correct volume', ...
             'range (between the dashed lines).', ...
             '', ...
             'A sentence will be repeated if your speech is', ...
             'too soft or too loud.', ...			
             '', ...
             'Press "OK" and then "Play" to start...', ...
             };

    elseif isequal(thisphase, 'pract2')		% pract2
        msg={'Good job!', ...
             '', ...
             'Now, in addition to the volume meter, you will', ...
             'see a speed indicator. ', ...
             '', ...
             'Please carefully adjust your speed to hit the', ...
             'area between the two dashed lines.', ...
             '', ...
             'A sentence will be repeated if your speech', ...
             'is too slow or too fast.', ...
             '', ...
             'Press "OK" and then "Play" to continue...', ...
             };

    elseif isequal(thisphase, 'pre')
        msg={'Great job!', ...
             '', ...
             'Now that you have mastered the required volume', ...
             'and speed, we will show you an indicator of the', ...
             'rhythmicity of your speech.', ...
             '', ...
             'This indicator will be shown only after the rhythmic', ...
             '(R) sentences.', ...
             '', ...
             'If you speak rhythmically, you should see the blnking', ...
             'bar appears above the dashed line. The more rhythmic your', ...
             'speech is, the higher the position of the bar will be.', ...
             '', ...
             'Press "OK" and then "Play" to continue...', ...
             };

    elseif isequal(thisphase, 'run1')
        msg={'Excellent! ', ...
             '', ...
             'We are about to begin the main part of the experiment.', ...
             '',...
             'Please stick to the volume, speed and rhythmicity you ', ...
             'have learned.',...
             '', ...
             'The volume and speed indicators will no longer be', ...
             'shown. But you will still see warning messages in ', ...
             'case you go out of the volume and/or speed ranges.', ...
             '', ...		
             'Press "OK" and then "Play" to continue...'};

    else
        runNum = str2double(strrep(thisphase, 'run', ''));
        msg={sprintf('Run #%d is coming up.', runNum), ...
             '', ...
             'You can take a break if you want.', ...
             '', ...
             'Keep up the good work!', ...
             '', ...
             'Press "OK" and then "Play" to continue...'};
    end
else % --- For fMRI sessions --- %
    if isequal(thisphase, 'pre')
        msg={'Hi, there!', ...
             '', ...
             'Before we start the first run of fMRI scans, ', ...
             'let''s do some practice sentences.', ...
             '', ...
             'Just as a reminder: ', ...
             'green font and "N" means natural speech;', ...
             'blue font and "R" means rhythmic speech.', ...       
             };

    elseif isequal(thisphase, 'run1')
        msg={'Excellent! We are about to start the first run', ...
             'of fMRI scans', ...
             '', ...
             'Please keep your head as still as possible', ...
             'throughout the run.',...
             '', ...
             'Unlike the practice trials, you will hear scanner', ...
             'noise between the trials.', ...
             '', ...
             'Enjoy!'};

    else
        runNum = str2double(strrep(thisphase, 'run', ''));
        msg={sprintf('Coming up: run #%d.', runNum), ...
             '', ...		
             'Keep up the good work and have fun!'};
    end
end
end
    
