function stcs = sents()
% Incomplete list of IEEE sentences
stcs = ...
     {'Glue the sheet to the dark blue background',...
      'It''s easy to tell the depth of a well',...
      'These days a chicken leg is a rare dish',...
      'Rice is often served in round bowls',...
      'The juice of lemons makes fine punch',...
      'The box was thrown beside the parked truck',...
      'Large size in stockings is hard to sell',...
      'The boy was there when the sun rose',...
      'A rod is used to catch pink salmon',...
      'The source of the huge river is the clear spring',...
      'Kick the ball straight and follow through',...
      'Help the woman get back to her feet',...
      'A pot of tea helps to pass the evening',...
      'Smoky fires lack flame and heat',...
      'The salt breeze came across from the sea',...
      'The girl at the booth sold fifty bonds',...
      'The small pup gnawed a hole in the sock',...
      'The swan dive was far short of perfect',...
      'The beauty of the view stunned the young boy',...
      'Two blue fish swam in the tank',...
      'Her purse was full of useless trash',...
      'The colt reared and threw the tall rider',...
      'Hoist the load to your left shoulder',...
      'Take the winding path to reach the lake',...
      'Note closely the size of the gas tank',...
      'Wipe the grease off his dirty face',...
      'Mend the coat before you go out',...
      'The stray cat gave birth to kittens',...
      'The pet cat gave birth to kittens',...
      'The active bat gave birth to pups',...
      'The clever bat gave birth to pups',...
      'The steady bat gave birth to pups',...
      'The young girl gave no clear response',...
      'The meal was done before the bell rang',...
      'A king ruled the state in the early days',...
      'The ship was torn apart on the sharp reef',...
      'Sickness kept him home the third week',...
      'The wide road shimmered in the hot sun',...
      'The lazy cow lay in the cool grass',...
      'Lift the square stone over the fence',...
      'The rope will bind the seven books at once',...
      'Hop over the fence and plunge in',...
      'The friendly gang left the drug store',...
      'The frosty air passed through the coat',...
      'Adding fast leads to wrong sums',...
      'The show was a flop from the very start',...
      'A saw is a tool used for making boards',...
      'March the soldiers past the next hill',...
      'A cup of sugar makes sweet fudge',...
      'Place a rosebush near the porch steps',...
      'Both lost their lives in the raging storm',...
      'We talked of the slide show in the circus',...
      'Use a pencil to write the first draft',...
      'He ran half way to the hardware store',...
      'The clock struck to mark the third period',...
      'The set of china hit the floor with a crash',...
      'This is a grand season for hikes on the road',...
      'The dune rose from the edge of the water',...
      'Those words were the cue for the actor to leave',...
      'A yacht slid around the point into the bay',...
      'The two met while playing on the sand',...
      'The lease ran out in sixteen weeks',...
      'The horn of the car woke the sleeping cop',...
      'The heart beat strongly and with firm strokes',...
      'The pearl was worn in a thin silver ring',...
      'The fruit peel was cut in thick slices',...
      'The Navy attacked the big task force',...
      'See the cat glaring at the scared mouse',...
      'There are more than two factors here',...
      'The hat brim was wide and too droopy',...
      'The lawyer tried to lose his case',...
      'Cut the pie into large parts',...
      'Men strive but seldom get rich',...
      'Always close the barn door tight',...
      'He lay prone and hardly moved a limb',...
      'A pound of sugar costs more than eggs',...
      'The fin was sharp and cut the clear water',...
      'The play seems dull and quite stupid',...
      'Bail the boat to stop it from sinking',...
      'The term ended late June that year',...
      'Ten pins were set in order',...
      'The bill was paid every third week',...
      'Oak is strong and also gives shade',...
      'Cats and dogs each hate the other',...
      'The pipe began to rust while new',...
      'Open the crate but don''t break the glass',...
      'Add the sum to the product of these three',...
      'Thieves who rob friends deserve jail',...
      'The ripe taste of cheese improves with age',...
      'Act on these orders with great speed',...
      'The hog crawled under the high fence',...
      'Move the vat over the hot fire',...
      'The bark of the pine tree was shiny and dark',...
      'Leaves turn brown and yellow in the fall',...
      'Split the log with a quick sharp blow',...
      'Burn peat after the logs give out',...
      'He ordered peach pie with ice cream',...
      'Weave the carpet on the right hand side',...
      'A lame back kept his score low',...
      'We find joy in the simplest things',...
      'Type out three lists of orders',...
      'The harder he tried the less he got done',...
      'The boss ran the show with a watchful eye',...
      'Paste can cleanse the most dirty brass',...
      'The slang word for raw whiskey is booze',...
      'It caught its hind paw in a rusty trap',...
      'The wharf could be seen at the farther shore',...
      'Feel the heat of the weak dying flame',...
      'The tiny girl took off her hat',...
      'A cramp is no small danger on a swim',...
      'He said the same phrase thirty times',...
      'Pluck the bright rose without leaves',...
      'Two plus seven is less than ten',...
      'Bring your problems to the wise chief',...
      'Write a fond note to the friend you cherish',...
      'We frown when events take a bad turn',...
      'The young kid jumped the rusty gate',...
      'Guess the results from the first scores',...
      'A salt pickle tastes fine with ham',...
      'The just claim got the right verdict',...
      'The tree top waved in a graceful way',...
      'The spot on the blotter was made by green ink',...
      'The cigar burned a hole in the desk top',...
      'The empty flask stood on the tin tray',...
      'A speedy man can beat this track mark',...
      'He broke a new shoelace that day',...
      'The coffee stand is too high for the couch',...
      'The urge to write short stories is rare',...
      'The pencils have all been used',...
      'The pirates seized the crew of the lost ship',...
      'We tried to replace the coin but failed',...
      'She sewed the torn coat quite neatly',...
      'The sofa cushion is red and of light weight',...
      'The jacket hung on the back of the wide chair',...
      'At that high level the air is pure',...
      'Drop the two when you add the figures',...
      'A filing case is now hard to buy',...
      'Wood is best for making toys and blocks',...
      'The office paint was a dull sad tan',...
      'He knew the skill of the great young actress',...
      'A rag will soak up spilled water',...
      'Steam hissed from the broken valve',...
      'The child almost hurt the small dog',...
      'There was a sound of dry leaves outside',...
      'Sunday is the best part of the week',...
      'The doctor cured him with these pills',...
      'The new girl was fired today at noon',...
      'Add the store''s account to the last cent',...
      'Acid burns holes in wool cloth',...
      'Fairy tales should be fun to write',...
      'Eight miles of woodland burned to waste',...
      'The third act was dull and tired the players',...
      'A young child should not suffer fright',...
      'Add the column and put the sum here',...
      'We admire and love a good cook',...
      'He carved a head from the round block of marble', ...
      'We mow our lawn all year', ...
      'We eat eels every day', ...
      'She sat at the top stair', ...
      'The puppy bit the tape', ...
      'Frank fought in the top ten'};   % Ends list 19  

% stcs = {'The birch canoe slid on the smooth planks', 'Glue the sheet to the dark blue background',...
%             'It''s easy to tell the depth of a well',    'These days a chicken leg is a rare dish',...
%             'Rice is often served in round bowls',       'The juice of lemons makes fine punch',...
%             'The box was thrown beside the parked truck','The hogs were fed chopped corn and garbage',...
%             'Four hours of steady work faced us',        'A large size in stockings is hard to sell',...
%             'The boy was there when the sun rose',       'A rod is used to catch pink salmon'...
%             'The source of the huge river is the clear spring', 'Kick the ball straight and follow through',...
%             'Help the woman get back to her feet',       'A pot of tea helps to pass the evening',...
%             'Smoky fires lack flame and heat',           'The soft cushion broke the man''s fall',...
%             'The salt breeze came across from the sea',  'The girl at the booth sold fifty bonds',...
%             'The small pup gnawed a hole in the sock',   'The fish twisted and turned on the bent hook',...
%             'Press the pants and sew a button on the vest', 'The swan dive was far short of perfect',...
%             'The beauty of the view stunned the young boy', 'Two blue fish swam in the tank',...
%             'Her purse was full of useless trash',          'The colt reared and threw the tall rider',...
%             'It snowed, rained, and hailed the same morning', 'Read verse out loud for pleasure',...
%             'Hoist the load to your left shoulder',      'Take the winding path to reach the lake',...
%             'Note closely the size of the gas tank',     'Wipe the grease off his dirty face',...
%             'Mend the coat before you go out',           'The wrist was badly strained and hung limp',...
%             'The stray cat gave birth to kittens',       'The young girl gave no clear response',...
%             'The meal was cooked before the bell rang',  'A king ruled the state in the early days',...
%             'The ship was torn apart on the sharp reef', 'Sickness kept him home the third week',...
%             'The wide road shimmered in the hot sun',    'The lazy cow lay in the cool grass',...
%             'Lift the square stone over the fence',      'The rope will bind the seven books at once',...
%             'Hop over the fence and plunge in',          'The friendly gang left the drug store',...
%             'Mesh wire keeps chicks inside',             'The frosty air passed through the coat',...
%             'The crooked maze failed to fool the mouse', 'Adding fast leads to wrong sums',...
%             'The show was a flop from the very start',   'A saw is a tool used for making boards',...
%             'The wagon moved on well oiled wheels',      'March the soldiers past the next hill',...
%             'A cup of sugar makes sweet fudge',          'Place a rosebush near the porch steps',...
%             'Both lost their lives in the raging storm', 'We talked of the slide show in the circus',...
%             'Use a pencil to write the first draft',     'He ran half way to the hardware store',...
%             'The clock struck to mark the third period', 'A small creek cut across the field',...
%             'Cars and busses stalled in snow drifts',    'The set of china hit the floor with a crash',...
%             'This is a grand season for hikes on the road', 'The dune rose from the edge of the water',...
%             'Those words were the cue for the actor to leave', 'A yacht slid around the point into the bay',...
%             'The two met while playing on the sand',     'The ink stain dried on the finished page',...
%             'The walled town was seized without a fight','The lease ran out in sixteen weeks',...
%             'A tame squirrel makes a nice pet',          'The horn of the car woke the sleeping cop',...
%             'The heart beat strongly and with firm strokes', 'The pearl was worn in a thin silver ring',...
%             'The fruit peel was cut in thick slices',    'The Navy attacked the big task force',...
%             };
  
% stcs = {'MESH MIRE KEEPS CHICKS INSIDE'};
% stcs = {'I OWE YOU A YO YO'};

% 'The grass curled around the fence post',...
return